# Generated by Django 3.0.6 on 2020-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('BusinessName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=50)),
                ('Telephone', models.IntegerField()),
            ],
        ),
    ]
