# Generated by Django 3.0.6 on 2020-05-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Busines',
        ),
    ]
